src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'Il y à déjà un compte avec ce pseudo !')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 50)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $actif = true;

    #[ORM\ManyToMany(targetEntity: Sortie::class, inversedBy: 'inscrits')]
    private Collection $sorties;

    #[ORM\OneToMany(mappedBy: 'organisateur', targetEntity: Sortie::class)]
    private Collection $sortiesOrganisees;

    #[ORM\ManyToOne(inversedBy: 'listeUtilisateurs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Campus $campus = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    public function __construct()
    {
        $this->sorties = new ArrayCollection();
        $this->sortiesOrganisees = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorties(Sortie $sorties): self
    {
        if (!$this->sorties->contains($sorties)) {
            $this->sorties->add($sorties);
        }

        return $this;
    }

    public function removeSorties(Sortie $sorties): self
    {
        $this->sorties->removeElement($sorties);

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSortiesOrganisees(): Collection
    {
        return $this->sortiesOrganisees;
    }

    public function addSortiesOrganisee(Sortie $sortiesOrganisee): self
    {
        if (!$this->sortiesOrganisees->contains($sortiesOrganisee)) {
            $this->sortiesOrganisees->add($sortiesOrganisee);
            $sortiesOrganisee->setOrganisateur($this);
        }

        return $this;
    }

    public function removeSortiesOrganisee(Sortie $sortiesOrganisee): self
    {
        if ($this->sortiesOrganisees->removeElement($sortiesOrganisee)) {
            // set the owning side to null (unless already changed)
            if ($sortiesOrganisee->getOrganisateur() === $this) {
                $sortiesOrganisee->setOrganisateur(null);
            }
        }

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }
}

src/Form/Recherche/ModelFiltre.php
<?php

namespace App\Form\Recherche;

use App\Entity\Campus;

class ModelFiltre
{

    private ?Campus $campus = null;
    private  ?string $nom = null;
    private ?bool $sortieOrganisateur = null;
    private ?bool $sortieInscrit = null;
    private ?bool $sortiePasInscrit = null;
    private ?bool $sortiePasses = null;

    private ?\DateTime $DateSortie = null;
    private ?\DateTime $DateCloture = null;

    public function __construct()
    {
    }

    /**
     * @return Campus|null
     */
    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    /**
     * @param Campus|null $campus
     */
    public function setCampus(?Campus $campus): void
    {
        $this->campus = $campus;
    }

    /**
     * @return string|null
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * @param string|null $nom
     */
    public function setNom(?string $nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return bool|null
     */
    public function getSortieOrganisateur(): ?bool
    {
        return $this->sortieOrganisateur;
    }

    /**
     * @param bool|null $sortieOrganisateur
     */
    public function setSortieOrganisateur(?bool $sortieOrganisateur): void
    {
        $this->sortieOrganisateur = $sortieOrganisateur;
    }

    /**
     * @return bool|null
     */
    public function getSortieInscrit(): ?bool
    {
        return $this->sortieInscrit;
    }

    /**
     * @param bool|null $sortieInscrit
     */
    public function setSortieInscrit(?bool $sortieInscrit): void
    {
        $this->sortieInscrit = $sortieInscrit;
    }

    /**
     * @return bool|null
     */
    public function getSortiePasInscrit(): ?bool
    {
        return $this->sortiePasInscrit;
    }

    /**
     * @param bool|null $sortiePasInscrit
     */
    public function setSortiePasInscrit(?bool $sortiePasInscrit): void
    {
        $this->sortiePasInscrit = $sortiePasInscrit;
    }

    /**
     * @return bool|null
     */
    public function getSortiePasses(): ?bool
    {
        return $this->sortiePasses;
    }

    /**
     * @param bool|null $sortiePasses
     */
    public function setSortiePasses(?bool $sortiePasses): void
    {
        $this->sortiePasses = $sortiePasses;
    }

    /**
     * @return \DateTime|null
     */
    public function getDateSortie(): ?\DateTime
    {
        return $this->DateSortie;
    }

    /**
     * @param \DateTime|null $DateSortie
     */
    public function setDateSortie(?\DateTime $DateSortie): void
    {
        $this->DateSortie = $DateSortie;
    }


    /**
     * @return \DateTime|null
     */
    public function getDateCloture(): ?\DateTime
    {
        return $this->DateCloture;
    }

    /**
     * @param \DateTime|null $DateCloture
     */
    public function setDateCloture(?\DateTime $DateCloture): void
    {
        $this->DateCloture = $DateCloture;
    }




}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Controller\LieuController;
use App\Entity\Campus;
use App\Entity\Lieu;
use App\Entity\Sortie;
use App\Entity\User;
use App\Entity\Ville;
use App\Repository\LieuRepository;
use App\Repository\SortieRepository;
use App\Repository\VilleRepository;
use ContainerPuhunFN\getVilleRepositoryService;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateIntervalType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SortieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom de la sortie :'
            ])
            ->add('campus', EntityType::class, [
                'label'=> 'Campus : ',
                'class' => Campus::class,
                'choice_label' => 'nom'
            ])

            ->add('ville', EntityType::class,[
                'label' => 'Ville :',
                'class'=> Ville::class,
                'choice_label' => 'nom',
                'placeholder' => 'Sélectionnez une ville',
                'mapped' => false,
                'query_builder' => function(VilleRepository $villeRepository) {
                    return $villeRepository
                        ->createQueryBuilder("v")->addOrderBy("v.nom");
                }
            ])

            ->add('lieu', EntityType::class,[
                'label' => 'Lieu :',
                'class'=> Lieu::class,
                'choice_label' => 'nom',
                'placeholder' => 'Sélectionnez un lieu',
//                'mapped' => false,
                'query_builder' => function(LieuRepository $lieuRepository ) {
                    return $lieuRepository
                        ->createQueryBuilder("l")
                        ->addOrderBy('l.nom');
                }
            ])

            ->add('dateHeureDebut', DateTimeType::class, [
                'label' => 'Date et heure :',
                'html5' => true,
                'widget' => 'single_text'
            ])
            ->add('duree', IntegerType::class)

            ->add('dateLimiteInscription', DateType::class, [
                'label' => 'Llimite d inscription :',
                'html5' => true,
                'widget' => 'single_text'
            ])
            ->add('nbInscriptionMax', IntegerType::class, [
                'label' => 'Nombre de places :'
            ])
            ->add('infosSortie', TextareaType::class, [
                'label' => 'Description :'
            ]);



            /*->add('campus', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'campus',
                'label' => 'Campus organisateur',
                /*  'query_builder' => function(SortieRepository $sortieRepository) {
                  $qb = $sortieRepository->createQueryBuilder("s");
                  $qb->addOrderBy("s.nom");
                  return $qb;
                  }
            ])*/

           /* ->add('codePostal', EntityType::class, [
                'class' => Ville::class,
                'label' => 'Code Postal',
                'choice_label' => function ($codePostal) {
                    return $codePostal->getCodePostal();
                }
            ])
        ->add('rue', EntityType::class, [
            'class' => Lieu::class,
            'label' => 'Rue',
            'choice_label' => function ($rue) {
                return $rue->getRue();
            }
        ]);*/

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }
}

templates/sortie/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Créer une sortie
{% endblock %}

{% block body %}
    <h2 class="h2perso mb-5">Créer une sortie</h2>

    <div class="creerSortie">
        {{ form_start(sortieForm) }}
        {{ form_label(sortieForm.nom) }}
        {{ form_widget(sortieForm.nom) }}
        {{ form_errors(sortieForm.nom) }}

        {{ form_label(sortieForm.ville) }}
        {{ form_widget(sortieForm.ville) }}
        {{ form_errors(sortieForm.ville) }}
        {{ form_label(sortieForm.lieu) }}
        {{ form_widget(sortieForm.lieu) }}
        {{ form_errors(sortieForm.lieu) }}
        <a class="link_button" href="{{ path('lieu_add') }}">Ajouter</a>

        {{ form_rest(sortieForm) }}
        <button class="btn btn-success">Enregistrer</button>
    </div>
    {{ form_end(sortieForm) }}
    <a href="{{ path('sortie_list') }}">
        <button class="btn btn-secondary">Annuler</button>
    </a>

    <style>

        .creerSortie {
            width: 460px;
        }

        label {
            width: 160px;
        }

        textarea,
        input {
            width: 200px;
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
        }

        input[type="number"] {
            width: 125px;
        }

        #sortie_duree_hour,
        #sortie_duree_minute{
            width: 80px;
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
        }

    </style>
{% endblock %}

templates/sortie/cancel.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Annuler la sortie "{{ sortie.nom }}"</h1>

    <div class="container detailsProfil">
        <div class="row">
            <div class="col-auto fw-bold">
                <div>Nom de la sortie :</div>
                <div>Date de la sortie :</div>
                <div>Campus :</div>
                <div>Lieu :</div>

            </div>
            <div class="col-auto">
                <div>{{ sortie.nom }}</div>
                <div>{{ sortie.dateHeureDebut | date('Y-m-d H:i:s') }}</div>
                <div>{{ sortie.campus.nom }}</div>
                <div>{{ sortie.lieu.nom }}</div>

            </div>
        </div>
    </div>

    {{ form_start(cancelSortieForm) }}

{#    {{ form_errors(cancelSortieForm) }}#}

    <div class="form-group">
        {{ form_label(cancelSortieForm.infosSortie) }}
        {{ form_widget(cancelSortieForm.infosSortie, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(cancelSortieForm.infosSortie) }}
    </div>

    <button type="submit" class="btn btn-danger">Annuler la sortie</button>

    {{ form_end(cancelSortieForm) }}

{% endblock %}

templates/sortie/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} | Accueil
{% endblock %}

{% block body %}


    <div class="container">
        <div class="infosAccueil">
            <p class="text-end">Date du jour : {{ "now"|date("d/m/Y") }} </p>
            <p class="text-end">Participant
                : {% if app.user %} {{ app.user.userIdentifier | capitalize }} {% endif %}</p>
        </div>

        <h3 class="mb-4">Filtrer les sorties</h3>

        {{ form_start(filtre, {'attr': {'class': 'form-inline'}}) }}

        <div class="row">

            <div class="col-auto">

                <div>
                    {{ form_label(filtre.campus, 'Campus :', {'label_attr': {'class': 'filtreLabel'}} ) }}
                    {{ form_widget(filtre.campus) }}
                </div>

                <div>
                    {{ form_label(filtre.nom, 'Le nom contient :', {'label_attr': {'class': 'filtreLabel'}}) }}
                    {{ form_widget(filtre.nom) }}
                </div>

                <div>
                    {{ form_label(filtre.dateSortie, 'Entre', {'label_attr': {'class': 'filtreLabelDate1'}}) }}
                    {{ form_widget(filtre.dateSortie) }}
                    {{ form_label(filtre.dateCloture, 'et', {'label_attr': {'class': 'filtreLabelDate2'}}) }}
                    {{ form_widget(filtre.dateCloture) }}
                </div>

            </div>

            <div class="col-auto">
                <div>
                    {{ form_widget(filtre.sortieOrganisateur, {'attr': {'class': 'form-check-input', 'id': 'sortieOrganisateur'}}) }}
                    {{ form_label(filtre.sortieOrganisateur, null, {'label_attr': {'class': 'form-check-label', 'for': 'sortieOrganisateur'}}) }}
                </div>

                <div>
                    {{ form_widget(filtre.sortieInscrit, {'attr': {'class': 'form-check-input', 'id': 'sortieInscrit'}}) }}
                    {{ form_label(filtre.sortieInscrit, null, {'label_attr': {'class': 'form-check-label', 'for': 'sortieInscrit'}}) }}
                </div>

                <div>
                    {{ form_widget(filtre.sortiePasInscrit, {'attr': {'class': 'form-check-input', 'id': 'sortiePasInscrit'}}) }}
                    {{ form_label(filtre.sortiePasInscrit, null, {'label_attr': {'class': 'form-check-label', 'for': 'sortiePasInscrit'}}) }}
                </div>

                <div>
                    {{ form_widget(filtre.sortiePasses, {'attr': {'class': 'form-check-input', 'id': 'sortiePasses'}}) }}
                    {{ form_label(filtre.sortiePasses, null, {'label_attr': {'class': 'form-check-label', 'for': 'sortiePasses'}}) }}
                </div>

            </div>

        </div>

        <button type="submit" class="btn btn-dark mb-5">Rechercher</button>
        <button type="reset" class="btn btn-dark mb-5">Effacer</button>

        {{ form_end(filtre) }}

        {#        {{ form_start(filtre) }} #}
        {#        {{ form_widget(filtre) }} #}
        {#        <button type="submit" class="Accueil btn btn-dark">Rechercher</button> #}
        {#        <button type="reset" class="Accueil btn btn-dark">Effacer</button> #}
        {#        {{ form_end(filtre) }} #}
    </div>

    <style>
        tbody {
            display: block;
            height: 330px; /* hauteur fixe du tbody */
            overflow-y: scroll; /* ajout d'une barre de défilement verticale */
        }
        tr {
            display: table;
            width: 100%;
            table-layout: fixed;
            /* autres styles des lignes de tableau si nécessaire */
        }
        th, td {
            width: auto;
            /* autres styles des cellules de tableau si nécessaire */
        }
    </style>
    </style>

    <div class="tablePerso">
        <table class="table text-center">
            <thead>
                <tr>
                    <th scope="col">Nom de la sortie</th>
                    <th scope="col">Date de la sortie</th>
                    <th scope="col">Clôture</th>
                    <th scope="col">Places</th>
                    <th scope="col">Etat</th>
                    <th scope="col">Inscrit</th>
                    <th scope="col">Organisateur</th>
                    <th colspan="2" scope="col" class="action">Action</th>
                </tr>
            </thead>

            <tbody>
            {% for sortie in sortieFiltre %}
                <tr>
                    <td colspan="1">{{ sortie.nom }}</td>
                    <td>{{ sortie.dateHeureDebut.format('d/m/Y H:i') }}</td>
                    <td>{{ sortie.dateLimiteInscription.format('d/m/Y H:i') }}</td>
                    <td>{{ sortie.inscrits|length }}/{{ sortie.nbInscriptionMax }}</td>
                    <td>
                        {{ sortie.etat.libelle }}
                    </td>
                    <td>
                        {% if sortie.inscrits.contains(app.user) and app.user.sorties.contains(sortie) and sortie.etat.libelle!='Clôturée' %}
                            X
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ path('user_show', {'id' : sortie.organisateur.id}) }}">{{ sortie.organisateur.username }}</a>
                    </td>
                    <td>
                        <div class="row">
                            <a href="{{ path('sortie_show', {'id': sortie.id}) }}">
                                <button class="btn btn-secondary btnAction">Afficher</button>
                            </a>
                        </div>
                        <div class="row">
                            {% if sortie.organisateur.id == app.user.id and sortie.etat.libelle == 'Créée' %}
                                <a href="{{ path('sortie_cancel', {'id': sortie.id}) }}">
                                    <button class="btn btn-danger btnAction">Annuler</button>
                                </a>
                            {% endif %}
                            {% if sortie.organisateur.id == app.user.id and sortie.etat.libelle == 'Ouverte' %}
                                <a href="{{ path('sortie_cancel', {'id': sortie.id}) }}">
                                    <button class="btn btn-danger btnAction">Annuler</button>
                                </a>
                            {% endif %}
                        </div>
                    </td>

                    <td>
                        <div class="row">
                            {% if sortie.inscrits.contains(app.user) and app.user.sorties.contains(sortie) and sortie.etat.libelle!='Clôturée' %}
                                <a href="{{ path('sortie_unsubscribe', {'id': sortie.id}) }}"
                                   class="btn btn-primary btnInscription">Se désinscrire
                                </a>
                            {% else %}
                                {% if sortie.etat.libelle == 'Ouverte' and sortie.inscrits.count < sortie.nbInscriptionMax %}
                                    <a href="{{ path('sortie_subscribe', {'id': sortie.id}) }}"
                                       class="btn btn-primary btnInscription">S'inscrire
                                    </a>
                                {% else %}
                                    <div style="height: 30px; width: 116px;"
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="row">
                            {% if sortie.organisateur.id == app.user.id and sortie.etat.libelle == 'Créée' %}
                                <a href="{{ path('sortie_update', {'id':sortie.id}) }}">
                                    <button class="warning btn btn-warning btnAction">Modifier</button>
                                </a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>


    <div>
        <a href="{{ path('sortie_add') }}">
            <button class="Accueil btn btn-dark" type="button">Créer une sortie</button>
        </a>
    </div>




{% endblock %}

templates/sortie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Détails de la sortie
{% endblock %}

{% block body %}
    <h2 class="h2perso mb-5">Détails de la sortie</h2>


    <div class="container">
        <table class="table tableauSortie">
            <tbody>
            <tr>
                <th scope="row">Nom de la sortie :</th>
                <td>{{ sortie.nom }}</td>
            </tr>
            <tr>
                <th scope="row">Date et heure :</th>
                <td>{{ sortie.dateHeureDebut | date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th scope="row">Date limite d'inscription :</th>
                <td>{{ sortie.dateLimiteInscription.format('d/m/Y H:i') }}</td>
            </tr>
            <tr>
                <th scope="row">Nombre de places :</th>
                <td>{{ sortie.inscrits|length }}/{{ sortie.nbInscriptionMax }}</td>
            </tr>
            <tr>
                <th scope="row">Durée :</th>
                <td>{{ sortie.duree | date('H:i:s') }}</td>
            </tr>
            <tr>
                <th scope="row">Description et infos :</th>
                <td>{{ sortie.infosSortie }}</td>
            </tr>
            <tr>
                <th scope="row">Campus :</th>
                <td>{{ sortie.campus.nom }}</td>
            </tr>
            <tr>
                <th scope="row">Ville :</th>
                <td>Rennes</td>
            </tr>
            <tr>
                <th scope="row">Lieu :</th>
                <td>{{ sortie.lieu.nom }}</td>
            </tr>
            <tr>
                <th scope="row">Rue :</th>
                <td>{{ sortie.lieu.rue }}</td>
            </tr>
            <tr>
                <th scope="row">Code postal :</th>
                <td>35000</td>
            </tr>
            </tbody>
        </table>
    </div>
    {#
    <div>Nom de la sortie {{ sortie.nom }}</div>
    <div>Date et heure : {{ sortie.dateHeureDebut | date('Y-m-d H:i:s') }}</div>
    <div>Date limite d'inscription : {{ sortie.dateLimiteInscription.format('d/m/Y H:i') }}</div>
    <div>Nombre de places : {{ sortie.inscrits|length }}/{{ sortie.nbInscriptionMax }}</div>
    <div>Durée : {{ sortie.duree | date('H:i:s') }}</div>
    <div>Description et infos : {{ sortie.infosSortie }}</div>
    <div>Campus : {{ sortie.campus.nom }}</div>
    <div>Lieu : {{ sortie.lieu.nom }}</div>
    <div>Rue : {{ sortie.lieu.rue }}</div>
    <div>Code postal :</div>
    <div>Clôture : {{ sortie.dateLimiteInscription | date('Y-m-d H:i:s') }}</div>
    #}
    <section class="inscrits">
        <h4 class="h2perso">Liste des participants inscrits :</h4>
        <table class="table text-center">
            <thead>
            <tr>
                <th scope="col">Pseudo</th>
                <th scope="col">Nom</th>
            </thead>
            <tbody>
            {% for inscrit in sortie.inscrits %}
                <tr>
                    <td><a href="{{ path('user_show', {'id' : inscrit.id}) }}">{{ inscrit.username }}</a></td>
                    <td>{{ inscrit.prenom ~ ' ' ~ inscrit.nom }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>

{% endblock %}

templates/sortie/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Modifier une sortie
{% endblock %}

{% block body %}
    <h2 class="h2perso mb-5">Modifier une sortie</h2>

<div class="center">
    <div class="largeurUpdate ">

        <div class="modifierSortie">

            {{ form_start(sortieForm) }}
            {{ form_label(sortieForm.nom) }}
            {{ form_widget(sortieForm.nom) }}
            {{ form_errors(sortieForm.nom) }}
            {{ form_rest(sortieForm) }}

        </div>
    </div>
    <div style="width: 400px">
        <div class="row mb-2">
            <div class="col-1">
            </div>
            <div class="col-4">
                <button class="btn btn-success cent">Enregistrer</button>
            </div>
            {{ form_end(sortieForm) }}
            <div class="col-2">
            </div>
            <div class="col-4">
                <form method="POST" action="{{ path("sortie_remove", {'id' : sortie.id }) }}"
                      onsubmit="return confirm('Confirmation de la suppression ?');">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('remove'~sortie.id) }}">
                    <button class="btn btn-danger cent" type="submit">Supprimer</button>
                </form>
            </div>
            <div class="col-1">
            </div>
        </div>

        <div class="row">
            <div class="col-1">
            </div>
            <div class="col-4">
                <a href="{{ path('sortie_publish', {'id':sortie.id}) }}">
                    <button class="btn btn-success cent" >Publier</button>
                </a>
            </div>
            <div class="col-2">
            </div>
            <div class="col-4">
                <a href="{{ path('sortie_list') }}">
                    <button class="btn btn-secondary cent">Retour</button>
                </a>
            </div>
        </div>
    </div>

</div>
{% endblock %}